name = "kukuverse-site"
compatibility_date = "2026-06-11"
pages_build_output_dir = "./frontend"

[vars]
RESEND_FROM = "KUKUVERSE <hello@example.com>"

[[d1_databases]]
binding = "DB"
database_name = "kukuverse-production"
database_id = "4819ec15-113f-4244-934e-f6d5fa96d5ec"
